### ISSUE TITLE
Renaming Based on date.

### ISSUE THREAD

**Issue by popykunju** [marc365/Windows-DesktopRecorder#2]
So the idea is to automatedly name the file based on       ######**dd-mm-yy** format when pressing the record button.

**Comment by marc365** [comment]
thanks for the idea - agreed, when wanting to recording multiple files successively, I have noticed the requester getting in the way myself - I like the append or overwrite option, so would want to keep that. I think that code uses a simple dialog requester that has limited options, so it would need an improved window with an added button with something like "New File" and that woud work for me I think, does this fit for what you are suggesting as well?

**Comment by popykunju** [comment]
To be precise, a button which automatically names the file with todays date. If the name repeats the button adds a numerical suffix.

**Comment by marc365** [comment]
yes, I've been thinking - will change it so if only a folder is selected and not a file it will save a new date named file there, and show no overwrite/append file requester. I will update it soon.
(edit: is numerical suffix prefered over using the time/seconds/milliseconds in the filename?)

**Comment by popykunju** [comment]
yes .The time can be ignored to simplify the filename. I respect your suggestions also.

**Comment by marc365** [comment]
Updated and published a release with the changes - should do what you need now - there is a date mode checkbox to do the functionality and some other updates.
